import type { FunctionInfo } from "../database.js";
import { escapeIdent, applyRoleMappings } from "./utils.js";

/**
 * Generate a complete SQL file content for a function
 */
export function generateFunctionSQL(
  func: FunctionInfo,
  roles?: string[],
  roleMappings?: Record<string, string>,
  includeDate: boolean = false,
): string {
  const lines: string[] = [];

  lines.push(`-- ========================================`);
  lines.push(`-- Function: ${func.schema_name}.${func.function_name}`);
  lines.push(`-- Generated by Tablerizer 🎲`);
  if (includeDate) {
    lines.push(`-- Date: ${new Date().toISOString()}`);
  }
  lines.push(`-- ========================================`);
  lines.push(`-- Type: ${func.function_type}`);
  lines.push(`-- Language: ${func.language}`);
  if (func.comment) {
    lines.push(`-- Comment: ${func.comment}`);
  }
  if (roles && roles.length > 0) {
    // Apply role mappings to roles in header for deterministic output
    const displayRoles =
      roleMappings && Object.keys(roleMappings).length > 0
        ? roles.map((role) => roleMappings[role] || role)
        : roles;
    lines.push(`-- Grants for roles: ${displayRoles.join(", ")}`);
  }
  lines.push("");

  // The function definition from PostgreSQL already includes CREATE OR REPLACE
  const funcDef = func.function_definition.trim();
  lines.push(funcDef.endsWith(";") ? funcDef : funcDef + ";");

  // Add comment if it exists
  if (func.comment) {
    lines.push("");
    lines.push(
      `COMMENT ON FUNCTION ${func.schema_name}.${func.function_name}(${func.function_arguments}) IS ${
        func.comment.includes("'")
          ? `$$${func.comment}$$`
          : `'${func.comment}'`
      };`,
    );
  }

  // Add GRANT EXECUTE statements for specified roles
  if (roles && roles.length > 0) {
    lines.push("");
    lines.push("-- Grant execution permissions");
    const sortedRoles = [...roles].sort();
    for (const role of sortedRoles) {
      lines.push(
        `GRANT EXECUTE ON FUNCTION ${func.schema_name}.${func.function_name}(${func.function_arguments}) TO ${escapeIdent(role)};`,
      );
    }
  }

  let content = lines.join("\n");

  if (roleMappings && Object.keys(roleMappings).length > 0) {
    content = applyRoleMappings(content, roleMappings);
  }

  return content;
}
