import type { FunctionData } from "../scanner.js";
import { escapeIdent } from "./utils.js";

export function generateFunctionSQL(
  data: FunctionData,
  includeDate: boolean = false,
): string {
  const func = data.info;
  const lines: string[] = [];

  lines.push(`-- ========================================`);
  lines.push(`-- Function: ${func.schema_name}.${func.function_name}`);
  lines.push(`-- Generated by Tablerizer 🎲`);
  if (includeDate) {
    lines.push(`-- Date: ${new Date().toISOString()}`);
  }
  lines.push(`-- ========================================`);
  lines.push(`-- Type: ${func.function_type}`);
  lines.push(`-- Language: ${func.language}`);
  if (func.comment) {
    lines.push(`-- Comment: ${func.comment}`);
  }
  if (data.grantRoles.length > 0) {
    lines.push(`-- Grants for roles: ${[...data.grantRoles].sort().join(", ")}`);
  }
  lines.push("");

  // The function definition from PostgreSQL already includes CREATE OR REPLACE
  const funcDef = func.function_definition.trim();
  lines.push(funcDef.endsWith(";") ? funcDef : funcDef + ";");

  // Add comment if it exists
  if (func.comment) {
    lines.push("");
    lines.push(
      `COMMENT ON FUNCTION ${func.schema_name}.${func.function_name}(${func.function_arguments}) IS ${
        func.comment.includes("'")
          ? `$$${func.comment}$$`
          : `'${func.comment}'`
      };`,
    );
  }

  // Add GRANT EXECUTE statements for specified roles
  if (data.grantRoles.length > 0) {
    lines.push("");
    lines.push("-- Grant execution permissions");
    const sortedRoles = [...data.grantRoles].sort();
    for (const role of sortedRoles) {
      lines.push(
        `GRANT EXECUTE ON FUNCTION ${func.schema_name}.${func.function_name}(${func.function_arguments}) TO ${escapeIdent(role)};`,
      );
    }
  }

  return lines.join("\n");
}
