import type { MaterializedViewInfo } from "../database.js";
import { escapeIdent, sectionHeader, applyRoleMappings } from "./utils.js";

/**
 * Generate documentation and grants for a materialized view
 */
export function generateMaterializedViewSQL(
  matview: MaterializedViewInfo,
  grants: Array<{
    grantor: string;
    grantee: string;
    privilege: string;
    is_grantable: boolean;
  }>,
  indexes: Array<{
    index_name: string;
    index_definition: string;
  }>,
  roleMappings?: Record<string, string>,
  includeDate: boolean = false,
): string {
  const lines: string[] = [];

  lines.push(`-- ========================================`);
  lines.push(
    `-- Materialized View: ${matview.schema_name}.${matview.matview_name}`,
  );
  lines.push(`-- Generated by Tablerizer 🎲`);
  if (includeDate) {
    lines.push(`-- Date: ${new Date().toISOString()}`);
  }
  lines.push(`-- ========================================`);
  lines.push(`-- Owner: ${matview.owner}`);
  lines.push(`-- Populated: ${matview.is_populated ? "Yes" : "No"}`);
  if (matview.comment) {
    lines.push(`-- Comment: ${matview.comment}`);
  }
  lines.push("");

  // Documentation section
  lines.push("/*");
  lines.push(
    `  MATERIALIZED VIEW DOCUMENTATION: ${matview.schema_name}.${matview.matview_name}`,
  );
  lines.push("  " + "=".repeat(65));
  lines.push("");

  if (matview.comment) {
    lines.push(`  Description: ${matview.comment}`);
    lines.push("");
  }

  lines.push(`  Owner: ${matview.owner}`);
  lines.push(
    `  Status: ${matview.is_populated ? "Populated" : "Not Populated"}`,
  );
  lines.push("");

  if (indexes.length > 0) {
    lines.push("  INDEXES:");
    lines.push("  --------");
    const sortedIndexes = [...indexes].sort((a, b) =>
      a.index_name.localeCompare(b.index_name),
    );
    for (const idx of sortedIndexes) {
      lines.push(`  • ${idx.index_name}`);
      lines.push(`    ${idx.index_definition}`);
    }
    lines.push("");
  }

  if (grants.length > 0) {
    lines.push("  PERMISSIONS:");
    lines.push("  ------------");
    const sortedGrants = [...grants].sort((a, b) => {
      const privilegeCompare = a.privilege.localeCompare(b.privilege);
      if (privilegeCompare !== 0) return privilegeCompare;
      return a.grantee.localeCompare(b.grantee);
    });
    for (const grant of sortedGrants) {
      const grantableText = grant.is_grantable ? " (GRANTABLE)" : "";
      lines.push(`  • ${grant.privilege} → ${grant.grantee}${grantableText}`);
    }
    lines.push("");
  }

  lines.push("  NOTE: This materialized view definition is not exported");
  lines.push("        as it's considered stateful. Only metadata and");
  lines.push("        permissions are documented here.");
  lines.push("*/");
  lines.push("");

  // Cleanup section
  lines.push(...sectionHeader("Cleanup (permission idempotency)"));
  lines.push("");

  if (grants.length > 0) {
    const grantees = new Set(grants.map((g) => g.grantee));
    const sortedGrantees = Array.from(grantees).sort();
    for (const grantee of sortedGrantees) {
      lines.push(
        `REVOKE ALL ON TABLE ${matview.schema_name}.${matview.matview_name} FROM ${escapeIdent(grantee)};`,
      );
    }
    lines.push("");
  }

  // Recreation section
  lines.push(...sectionHeader("Grants"));
  lines.push("");

  if (grants.length > 0) {
    const sortedGrants = [...grants].sort((a, b) => {
      const granteeCompare = a.grantee.localeCompare(b.grantee);
      if (granteeCompare !== 0) return granteeCompare;
      return a.privilege.localeCompare(b.privilege);
    });
    for (const grant of sortedGrants) {
      let sql = `GRANT ${grant.privilege} ON TABLE ${matview.schema_name}.${matview.matview_name} TO ${escapeIdent(grant.grantee)}`;
      if (grant.is_grantable) {
        sql += " WITH GRANT OPTION";
      }
      sql += ";";
      lines.push(sql);
    }
    lines.push("");
  }

  let content = lines.join("\n");

  if (roleMappings && Object.keys(roleMappings).length > 0) {
    content = applyRoleMappings(content, roleMappings);
  }

  return content;
}
