import { sectionHeader, applyRoleMappings } from "./utils.js";
import type { TableData } from "./types.js";
import { generateDropTableSQL, generateCreateTableSQL, generateOwnerSQL } from "./table-ddl.js";
import { generateConstraintsSQL } from "./constraints.js";
import { generateIndexesSQL } from "./indexes.js";
import { generateCommentsSQL, generateIndexCommentsSQL } from "./comments.js";
import { generateRlsSQL } from "./rls.js";
import { generateGrantsSQL, generateColumnGrantsSQL } from "./grants.js";
import { generateTriggersSQL } from "./triggers.js";

/**
 * Generate a complete, idempotent SQL file for a table.
 *
 * Sections (in order):
 *   1. Header
 *   2. DROP TABLE
 *   3. CREATE TABLE
 *   4. OWNER
 *   5. CONSTRAINTS (DROP IF EXISTS + ADD)
 *   6. INDEXES (DROP IF EXISTS + CREATE)
 *   7. COMMENTS (TABLE + COLUMN + INDEX)
 *   8. ROW LEVEL SECURITY (ENABLE + POLICIES)
 *   9. GRANTS (TABLE-LEVEL + COLUMN-LEVEL)
 *  10. TRIGGERS (DROP IF EXISTS + CREATE)
 */
export function generateTableSQL(
  schema: string,
  tableData: TableData,
  roleMappings?: Record<string, string>,
  includeDate: boolean = false,
): string {
  const tableName = tableData.table;
  const sections: string[] = [];

  // ---- HEADER ----
  sections.push(`-- ========================================`);
  sections.push(`-- Table: ${schema}.${tableName}`);
  sections.push(`-- Generated by Tablerizer 🎲`);
  if (includeDate) {
    sections.push(`-- Date: ${new Date().toISOString()}`);
  }
  sections.push(`-- ========================================`);
  sections.push("");

  // ---- DROP TABLE ----
  sections.push(...sectionHeader("DROP (idempotent cleanup)"));
  sections.push("");
  sections.push(...generateDropTableSQL(schema, tableName));
  sections.push("");

  // ---- CREATE TABLE ----
  sections.push(...sectionHeader("CREATE TABLE"));
  sections.push("");
  sections.push(
    ...generateCreateTableSQL(
      schema,
      tableName,
      tableData.column_definitions,
      tableData.partition_info,
    ),
  );
  sections.push("");

  // ---- OWNER ----
  sections.push(...sectionHeader("OWNER"));
  sections.push("");
  sections.push(...generateOwnerSQL(schema, tableName, tableData.owner));
  sections.push("");

  // ---- CONSTRAINTS ----
  const constraintsSQL = generateConstraintsSQL(
    schema,
    tableName,
    tableData.constraint_definitions,
  );
  if (constraintsSQL.length > 0) {
    sections.push(...sectionHeader("CONSTRAINTS"));
    sections.push("");
    sections.push(...constraintsSQL);
    sections.push("");
  }

  // ---- INDEXES ----
  const indexesSQL = generateIndexesSQL(schema, tableData.index_definitions);
  if (indexesSQL.length > 0) {
    sections.push(...sectionHeader("INDEXES"));
    sections.push("");
    sections.push(...indexesSQL);
    sections.push("");
  }

  // ---- COMMENTS ----
  const commentsSQL = generateCommentsSQL(
    schema,
    tableName,
    tableData.comment,
    tableData.column_definitions,
  );
  const indexCommentsSQL = generateIndexCommentsSQL(
    schema,
    tableData.index_definitions,
  );
  if (commentsSQL.length > 0 || indexCommentsSQL.length > 0) {
    sections.push(...sectionHeader("COMMENTS"));
    sections.push("");
    if (commentsSQL.length > 0) {
      sections.push(...commentsSQL);
    }
    if (indexCommentsSQL.length > 0) {
      sections.push(...indexCommentsSQL);
    }
    sections.push("");
  }

  // ---- ROW LEVEL SECURITY ----
  if (tableData.rls.enabled || tableData.rls.policies.length > 0) {
    const rlsSQL = generateRlsSQL(
      schema,
      tableName,
      tableData.rls.enabled,
      tableData.rls.force,
      tableData.rls.policies,
    );
    if (rlsSQL.length > 0) {
      sections.push(...sectionHeader("ROW LEVEL SECURITY"));
      sections.push("");
      sections.push(...rlsSQL);
      sections.push("");
    }
  }

  // ---- GRANTS ----
  const tableGrantsSQL = generateGrantsSQL(
    schema,
    tableName,
    tableData.rbac.table_grants,
  );
  const columnGrantsSQL = generateColumnGrantsSQL(
    schema,
    tableName,
    tableData.rbac.column_grants,
  );
  if (tableGrantsSQL.length > 0 || columnGrantsSQL.length > 0) {
    sections.push(...sectionHeader("GRANTS"));
    sections.push("");
    if (tableGrantsSQL.length > 0) {
      sections.push("-- Table-level grants");
      sections.push(...tableGrantsSQL);
    }
    if (columnGrantsSQL.length > 0) {
      if (tableGrantsSQL.length > 0) sections.push("");
      sections.push("-- Column-level grants");
      sections.push(...columnGrantsSQL);
    }
    sections.push("");
  }

  // ---- TRIGGERS ----
  const triggersSQL = generateTriggersSQL(
    schema,
    tableName,
    tableData.triggers,
  );
  if (triggersSQL.length > 0) {
    sections.push(...sectionHeader("TRIGGERS"));
    sections.push("");
    sections.push(...triggersSQL);
    sections.push("");
  }

  let content = sections.join("\n");

  // Apply role mappings if provided
  if (roleMappings && Object.keys(roleMappings).length > 0) {
    content = applyRoleMappings(content, roleMappings);
  }

  return content;
}
